<?php
/**
 * Created by PhpStorm.
 * User: максим
 * Date: 21.08.2018
 * Time: 16:19
 */

namespace app\commands;


use app\models\Event;
use yii\console\Controller;
use yii\console\ExitCode;
use yii\db\ActiveRecord;
use yii\helpers\BaseArrayHelper;
use yii\helpers\Console;

class MaxController extends Controller
{
    public $foo=[];
    public $bar;

    public function actionIndex(): int
    {
        echo 'Hi, Max';
        return ExitCode::OK;
    }

    public function options($actionID) : array
    {

        $options = parent::options($actionID); // TODO: Change the autogenerated stub
        if ($actionID === 'options') {
            $options = BaseArrayHelper::merge($options, [
                    'foo',
                    'bar',
                ]);
        };
        return $options;
    }

    public function actionOptions() : int
    {
        var_dump($this->foo, $this->bar);
        return ExitCode::OK;
    }

    public function actionCount(string $className): int
    {
        if (!\is_subclass_of($className, ActiveRecord::class))
            $msg = sprintf("Class %s is not subclass of ActiveRecord\n", $className);
        echo $this->ansiFormat($msg, Console::BG_CYAN);
        //var_dump($className);exit;
        //$count = Event::find()->count('id');
        //echo sprintf("Total of %s is: %d\n", Event::class, $count);
        return ExitCode::OK;
    }
}